[package]
name = "tutorlolv2"
version = "0.7.1"
edition = "2024"
authors = ["Luiz Gustavo Santana Dias Gomes"]
repository = "https://github.com/LuizGomes56/tutorlolv2"
description = "League of Legends static library that evaluates damages of abilities, passives, items, and runes"

[dependencies]
bincode = {
  version = "2.0.1",
  default-features = false,
  features = [
    "alloc",
    "derive",
  ]
}
const_sized_bit_set = "0.5.0"
serde = {
  version = "1.0",
  default-features = false,
  features = [
    "alloc",
    "derive",
  ]
}
serde_arrays = { version = "0.2.0", default-features = false }
tutorlolv2_gen = { path = "tutorlolv2_gen" }

[build-dependencies]
tutorlolv2_build_dep = { path = "build" }
