[package]
name = "tutorlolv2_dev"
version = "0.4.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
heck = "0.5.0"
reqwest = { version = "0.12.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
tokio = {
  version = "1.49.0",
  default-features = false,
  features = ["macros", "rt-multi-thread"]
}
tutorlolv2_types = { path = "../tutorlolv2_types", features = ["dev"] }
