//! This module is automatically generated by the crate [`tutorlolv2_build`].
//! It contains thousands of static variables and constants that are used
//! to evaluate the damage of abilities, items, runes, and champions, as well
//! as to provide methods and enums that avoid the usage of the type [`str`]
//! directly, replacing it by a numeric enums, that are encoded and decoded
//! by both frontend and backend.
//!
//! Part of the code generated is exported and used directly by the frontend
//! as a dependency library. Note everything in this module has a `const` or
//! `static` qualifier, since everything is known at compile-time

pub mod champions;
pub mod items;
pub mod runes;

pub(crate) use crate::{cache::*, enums::*, eval::*};
pub(crate) use bincode::{Decode, Encode};
pub use champions::*;
pub use items::*;
pub use runes::*;
pub(crate) use serde::{Deserialize, Serialize};
pub(crate) use tutorlolv2_types::*;

impl ChampionId {
    pub const fn number_of_spells(&self) -> usize {
        let champion = CHAMPION_CACHE[*self as usize];
        champion.closures.len()
    }
}
