[package]
name = "shared_types"
version = "0.1.0"
edition = "2024"

[dependencies]
paste = "1.0.15"
phf = { version = "0.12.1", features = ["macros"] }
serde = { version = "1.0.219", features = ["derive"] }
