use crate::{CtxVar, yew::render::FormulaRenderer};
use alloc::string::String;
use tutorlolv2_codec::{Bracket, Class, Highlighter};
use tutorlolv2_types::AdaptiveType;

impl FormulaRenderer {
    pub fn tower_global() -> String {
        let mut h = Highlighter::new();

        h.global_struct("Tower")
            .html_field("damage_type", &{
                let mut h = Highlighter::new();

                h.push(Class::Control, "match")
                    .raw(" ")
                    .push(Class::Number, 0.35)
                    .raw(" * ")
                    .push(Class::Variable, &CtxVar::BonusAd.to_snake_case())
                    .raw(" | ")
                    .push(Class::Number, 0.2)
                    .raw(" * ")
                    .push(Class::Variable, &CtxVar::AbilityPower.to_snake_case())
                    .raw(" ")
                    .bracket(Bracket::LCurly)
                    .raw("\n\t\t")
                    .push(Class::Variable, "lhs")
                    .raw(" > ")
                    .push(Class::Variable, "rhs")
                    .raw(" => ")
                    .push(Class::Constant, AdaptiveType::Physical)
                    .raw(",\n\t\t")
                    .push(Class::Variable, "lhs")
                    .raw(" < ")
                    .push(Class::Variable, "rhs")
                    .raw(" => ")
                    .push(Class::Constant, AdaptiveType::Magic)
                    .raw(",\n\t\t")
                    .push(Class::Control, "else")
                    .raw(" => ")
                    .push(Class::Type, "ChampionId")
                    .raw("::")
                    .push(Class::Function, "adaptive_type")
                    .raw(",\n\t")
                    .bracket(Bracket::RCurly);

                h.into_fragment()
            })
            .html_field("ref", &{
                let mut h = Highlighter::new();

                h.push(Class::Type, "tutorlolv2")
                    .raw("::")
                    .push(Class::Type, "model")
                    .raw("::")
                    .push(Class::Type, "RiotFormulas")
                    .raw("::")
                    .push(Class::Function, "tower_damage");

                h.into_fragment()
            })
            .finish_struct();

        h.into_fragment()
    }

    pub fn tower_fn() -> String {
        let mut h = Highlighter::new();

        h.push(Class::Keyword, "fn")
            .raw(" ")
            .push(Class::Type, "tutorlolv2")
            .raw("::")
            .push(Class::Type, "model")
            .raw("::")
            .push(Class::Function, "TowerDamage")
            .bracket(Bracket::LParen)
            .raw("...")
            .bracket(Bracket::RParen)
            .raw(" ")
            .bracket(Bracket::LCurly)
            .raw("\n\t")
            .push(Class::Keyword, "let")
            .raw(" ")
            .push(Class::Variable, "base")
            .raw(" = ")
            .push(Class::Variable, CtxVar::BaseAd.to_snake_case())
            .raw("\n\t\t+ ")
            .push(Class::Variable, CtxVar::BonusAd.to_snake_case())
            .raw("\n\t\t+ ")
            .push(Class::Variable, CtxVar::AbilityPower.to_snake_case())
            .raw(" * ")
            .push(Class::Number, 0.6)
            .raw(";\n\n\t")
            .push(Class::Keyword, "let")
            .raw(" ")
            .push(Class::Variable, "bonus_resist")
            .raw(" = ")
            .push(Class::Number, 15)
            .raw(" + ")
            .push(Class::Number, 50)
            .raw(" * ")
            .bracket(Bracket::LParen)
            .push(Class::Variable, "plates")
            .raw(" - ")
            .push(Class::Number, 1)
            .bracket(Bracket::RParen)
            .raw(";\n\n\t")
            .push(Class::Control, "if")
            .raw(" ")
            .push(Class::Variable, "plates")
            .raw(" == ")
            .push(Class::Number, 0)
            .raw(" ")
            .bracket(Bracket::LCurly)
            .raw("\n\t\t")
            .push(Class::Variable, "bonus_resist")
            .raw(" = ")
            .push(Class::Number, 0)
            .raw(";\n\t")
            .bracket(Bracket::RCurly)
            .raw("\n\n\t")
            .push(Class::Keyword, "let")
            .raw(" ")
            .push(Class::Variable, "raw_resist")
            .raw(" = ")
            .push(Class::Number, 40)
            .raw(" + ")
            .push(Class::Variable, "bonus_resist")
            .raw(";\n\t")
            .push(Class::Keyword, "let")
            .raw(" ")
            .push(Class::Variable, "resist")
            .raw(" = ")
            .push(Class::Variable, "raw_resist")
            .raw("\n\t\t* ")
            .bracket(Bracket::LParen)
            .push(Class::Number, 1)
            .raw(" - ")
            .push(Class::Variable, "pen_percent")
            .raw(" / ")
            .push(Class::Number, 100)
            .bracket(Bracket::RParen)
            .raw("\n\t\t- ")
            .push(Class::Variable, "pen_flat")
            .raw(";\n\n\t")
            .push(Class::Keyword, "let")
            .raw(" ")
            .push(Class::Variable, "mult")
            .raw(" = ")
            .push(Class::Number, 100)
            .raw(" / ")
            .bracket(Bracket::LParen)
            .push(Class::Number, 100)
            .raw(" + ")
            .push(Class::Variable, "resist")
            .bracket(Bracket::RParen)
            .raw(";\n\t")
            .push(Class::Variable, "base")
            .raw(" * ")
            .push(Class::Variable, "mult")
            .raw("\n")
            .bracket(Bracket::RCurly);

        h.into_fragment()
    }
}
