use crate::{
    ENV_CONFIG, JsonRead, JsonWrite, MayFail,
    client::{SaveTo, Tag},
    gen_utils::RegExtractor,
    generators::{Generator, gen_decl::decl_items::*},
    items::{Effect, Item, ItemStats, MerakiItem},
    riot::RiotCdnItem,
};
use rayon::iter::{IntoParallelIterator, ParallelIterator};
use serde_json::Value;
use tutorlolv2_gen::{Attrs, CastId, DamageType, ItemId, StatName};

pub struct ItemData {
    pub meraki_data: Option<MerakiItem>,
    pub riot_data: RiotCdnItem,
    pub current_data: Item,
}

impl ItemData {
    /// Creates a new struct that serves as argument for the item generator functions
    pub const fn new(
        meraki_data: Option<MerakiItem>,
        riot_data: RiotCdnItem,
        current_data: Item,
    ) -> Self {
        Self {
            meraki_data,
            riot_data,
            current_data,
        }
    }

    pub fn infer_stats_ifdef(&mut self) {
        let data = &mut self.current_data;
        let ItemStats {
            adaptive_force,
            ability_power,
            armor,
            armor_penetration,
            magic_penetration,
            attack_damage,
            attack_speed,
            crit_chance,
            crit_damage,
            health,
            lifesteal,
            magic_resistance,
            mana,
            movespeed,
            omnivamp,
        } = &mut data.stats;
        const fn assign(stat: &mut f64, value: u16) {
            *stat = value as _;
        }
        for (s, value) in &data.prettified_stats {
            let v = *value;
            match s {
                StatName::AdaptiveForce => *adaptive_force = v as _,
                StatName::AbilityPower => assign(&mut ability_power.flat, v),
                StatName::Armor => assign(&mut armor.flat, v),
                StatName::ArmorPenetration => assign(&mut armor_penetration.percent, v),
                StatName::AttackDamage => assign(&mut attack_damage.flat, v),
                StatName::AttackSpeed => assign(&mut attack_speed.flat, v),
                StatName::CritChance => assign(&mut crit_chance.flat, v),
                StatName::CritDamage => assign(&mut crit_damage.flat, v),
                StatName::Health => assign(&mut health.flat, v),
                StatName::Lethality => assign(&mut armor_penetration.flat, v),
                StatName::LifeSteal => assign(&mut lifesteal.flat, v),
                StatName::MagicPenetration => assign(&mut magic_penetration.flat, v),
                StatName::MagicResist => assign(&mut magic_resistance.flat, v),
                StatName::Mana => assign(&mut mana.flat, v),
                StatName::MoveSpeed => assign(&mut movespeed.flat, v),
                StatName::Omnivamp => assign(&mut omnivamp.flat, v),
                _ => {}
            }
        }
    }

    pub fn yield_to(&mut self, item_id: ItemId) -> MayFail {
        let data = ItemFactory::run(item_id)?;
        self.current_data.melee = data.current_data.melee;
        self.current_data.ranged = data.current_data.ranged;
        self.damage_type(data.current_data.damage_type);
        self.infer_stats_ifdef();
        Ok(())
    }

    fn meraki_data(&self) -> MayFail<&MerakiItem> {
        let riot_id = self.current_data.riot_id;
        let item_name = &self.current_data.name;
        self.meraki_data
            .as_ref()
            .ok_or(format!("No meraki_data for item {item_name} ({riot_id})").into())
    }

    /// Returns the damage of the `passive` or `active` effect in the field `field`
    fn effect_damage(&self, from: &[Effect], offset: usize, field: &str) -> MayFail<String> {
        let name = &self.meraki_data()?.name;
        Ok(from
            .get(offset)
            .ok_or(format!(
                "[{name}]: meraki_data.{field}[{offset}] does not exist"
            ))?
            .effects
            .get_damage())
    }

    /// Returns the damage of the `passive` effect in the field `passives`
    pub fn passive(&self, offset: usize) -> MayFail<String> {
        self.effect_damage(&self.meraki_data()?.passives, offset, "passives")
    }

    /// Returns the damage of the `active` effect in the field `active`
    pub fn active(&self, offset: usize) -> MayFail<String> {
        self.effect_damage(&self.meraki_data()?.active, offset, "active")
    }

    /// Sets some attribute for the current item
    pub const fn attr(&mut self, attr: Attrs) {
        self.current_data.attributes = attr;
    }

    /// Sets the damage type of the current item
    pub const fn damage_type(&mut self, damage_type: DamageType) {
        self.current_data.damage_type = damage_type;
    }

    /// Sets the damage only for the `melee` and `minimum_damage` fields
    pub fn melee_min_dmg<S: AsRef<str>>(&mut self, dmg: S) {
        self.current_data.melee.minimum_damage = dmg.as_ref().to_string();
    }

    /// Sets the damage only for the `melee` and `maximum_damage` fields
    pub fn melee_max_dmg<S: AsRef<str>>(&mut self, dmg: S) {
        self.current_data.melee.maximum_damage = dmg.as_ref().to_string();
    }

    /// Sets the damage only for the `ranged` and `minimum_damage` fields
    pub fn ranged_min_dmg<S: AsRef<str>>(&mut self, dmg: S) {
        self.current_data.ranged.minimum_damage = dmg.as_ref().to_string();
    }

    /// Sets the damage only for the `ranged` and `maximum_damage` fields
    pub fn ranged_max_dmg<S: AsRef<str>>(&mut self, dmg: S) {
        self.current_data.ranged.maximum_damage = dmg.as_ref().to_string();
    }

    /// Sets only the `minimum_damage` field for both `melee` and `ranged` fields
    pub fn const_min_dmg<S: AsRef<str>>(&mut self, dmg: S) {
        self.melee_min_dmg(&dmg);
        self.ranged_min_dmg(dmg);
    }

    /// Sets only the `maximum_damage` field for both `melee` and `ranged` fields
    pub fn const_max_dmg<S: AsRef<str>>(&mut self, dmg: S) {
        self.melee_max_dmg(&dmg);
        self.ranged_max_dmg(dmg);
    }

    /// Sets the `minimum_damage` and `maximum_damage` to both `melee` and `ranged`
    /// fields according to the provided values
    pub fn const_dmg<S: AsRef<str>>(&mut self, min_dmg: S, max_dmg: S) {
        self.const_min_dmg(min_dmg);
        self.const_max_dmg(max_dmg);
    }
}

pub struct ItemFactory;

impl ItemFactory {
    pub const GENERATOR_FOLDER: &str = "tutorlolv2_dev/src/generators/gen_items";

    const fn function(item_id: ItemId) -> fn(ItemData) -> Box<dyn Generator<ItemData>> {
        match item_id {
            ItemId::AbyssalMask => AbyssalMask::new,
            ItemId::AbyssalMaskArena => AbyssalMaskArena::new,
            ItemId::AbyssalMaskU32 => AbyssalMaskU32::new,
            ItemId::Actualizer => Actualizer::new,
            ItemId::ActualizerArena => ActualizerArena::new,
            ItemId::AdaptiveHelmArena => AdaptiveHelmArena::new,
            ItemId::AegisOfTheLegion => AegisOfTheLegion::new,
            ItemId::AegisOfTheLegionArena => AegisOfTheLegionArena::new,
            ItemId::AetherWisp => AetherWisp::new,
            ItemId::AmplifyingTome => AmplifyingTome::new,
            ItemId::AnathemasChains => AnathemasChains::new,
            ItemId::AnathemasChainsArena => AnathemasChainsArena::new,
            ItemId::AnimaEcho => AnimaEcho::new,
            ItemId::Animapocalypse => Animapocalypse::new,
            ItemId::AniMines => AniMines::new,
            ItemId::AntiSharkSeaMine => AntiSharkSeaMine::new,
            ItemId::AntiTowerSocks => AntiTowerSocks::new,
            ItemId::AnvilVoucherArena => AnvilVoucherArena::new,
            ItemId::ArcaneSweeper => ArcaneSweeper::new,
            ItemId::ArchangelsStaff => ArchangelsStaff::new,
            ItemId::ArchangelsStaffArena => ArchangelsStaffArena::new,
            ItemId::ArchangelsStaffU32 => ArchangelsStaffU32::new,
            ItemId::ArdentCenser => ArdentCenser::new,
            ItemId::ArdentCenserArena => ArdentCenserArena::new,
            ItemId::ArdentCenserU32 => ArdentCenserU32::new,
            ItemId::ArmoredAdvance => ArmoredAdvance::new,
            ItemId::AtmasReckoning => AtmasReckoning::new,
            ItemId::AtmasReckoningArena => AtmasReckoningArena::new,
            ItemId::AtmasReckoningU66 => AtmasReckoningU66::new,
            ItemId::AxiomArc => AxiomArc::new,
            ItemId::AxiomArcArena => AxiomArcArena::new,
            ItemId::BamisCinder => BamisCinder::new,
            ItemId::BandleglassMirror => BandleglassMirror::new,
            ItemId::BandleJuiceOfHaste => BandleJuiceOfHaste::new,
            ItemId::BandleJuiceOfPower => BandleJuiceOfPower::new,
            ItemId::BandleJuiceOfVitality => BandleJuiceOfVitality::new,
            ItemId::Bandlepipes => Bandlepipes::new,
            ItemId::BandlepipesArena => BandlepipesArena::new,
            ItemId::BansheesVeil => BansheesVeil::new,
            ItemId::BansheesVeilArena => BansheesVeilArena::new,
            ItemId::Bastionbreaker => Bastionbreaker::new,
            ItemId::BattleBunnyCrossbow => BattleBunnyCrossbow::new,
            ItemId::BattleCatBarrage => BattleCatBarrage::new,
            ItemId::BearfootChemDispenser => BearfootChemDispenser::new,
            ItemId::BerserkersGreaves => BerserkersGreaves::new,
            ItemId::BerserkersGreavesArena => BerserkersGreavesArena::new,
            ItemId::BFSword => BFSword::new,
            ItemId::BFSwordArena => BFSwordArena::new,
            ItemId::BlackCleaver => BlackCleaver::new,
            ItemId::BlackCleaverArena => BlackCleaverArena::new,
            ItemId::BlackfireTorch => BlackfireTorch::new,
            ItemId::BlackfireTorchArena => BlackfireTorchArena::new,
            ItemId::BlackHoleGauntletU44 => BlackHoleGauntletU44::new,
            ItemId::BlackMistScythe => BlackMistScythe::new,
            ItemId::BladeOfTheRuinedKing => BladeOfTheRuinedKing::new,
            ItemId::BladeOfTheRuinedKingArena => BladeOfTheRuinedKingArena::new,
            ItemId::BladeORang => BladeORang::new,
            ItemId::BlastingWand => BlastingWand::new,
            ItemId::BlastingWandArena => BlastingWandArena::new,
            ItemId::BlightingJewel => BlightingJewel::new,
            ItemId::BloodlettersCurse4010 => BloodlettersCurse4010::new,
            ItemId::BloodlettersCurse8010 => BloodlettersCurse8010::new,
            ItemId::Bloodsong => Bloodsong::new,
            ItemId::Bloodthirster => Bloodthirster::new,
            ItemId::BloodthirsterArena => BloodthirsterArena::new,
            ItemId::Boots => Boots::new,
            ItemId::BootsOfSwiftness => BootsOfSwiftness::new,
            ItemId::BootsOfSwiftnessArena => BootsOfSwiftnessArena::new,
            ItemId::BotLaneQuest1202 => BotLaneQuest1202::new,
            ItemId::BotLaneQuest1207 => BotLaneQuest1207::new,
            ItemId::BountyOfWorlds => BountyOfWorlds::new,
            ItemId::BrambleVest => BrambleVest::new,
            ItemId::BraveryVoucherArena => BraveryVoucherArena::new,
            ItemId::BulwarkOfTheMountain => BulwarkOfTheMountain::new,
            ItemId::BunnyHop => BunnyHop::new,
            ItemId::BunnyMegaBlast => BunnyMegaBlast::new,
            ItemId::BunnyPrimeBallista => BunnyPrimeBallista::new,
            ItemId::CappaJuice => CappaJuice::new,
            ItemId::CappaJuiceArena => CappaJuiceArena::new,
            ItemId::CarrotCrash => CarrotCrash::new,
            ItemId::CatalystOfAeons => CatalystOfAeons::new,
            ItemId::CaulfieldsWarhammer => CaulfieldsWarhammer::new,
            ItemId::CelestialOpposition => CelestialOpposition::new,
            ItemId::ChainlacedCrushers => ChainlacedCrushers::new,
            ItemId::ChainVest => ChainVest::new,
            ItemId::ChainVestArena => ChainVestArena::new,
            ItemId::ChaliceOfBlessing => ChaliceOfBlessing::new,
            ItemId::ChempunkChainsword => ChempunkChainsword::new,
            ItemId::ChempunkChainswordArena => ChempunkChainswordArena::new,
            ItemId::ChemtechPutrifier => ChemtechPutrifier::new,
            ItemId::ChemtechPutrifierArena => ChemtechPutrifierArena::new,
            ItemId::CloakOfAgility => CloakOfAgility::new,
            ItemId::CloakOfStarryNightU44 => CloakOfStarryNightU44::new,
            ItemId::CloakOfStarryNightU66 => CloakOfStarryNightU66::new,
            ItemId::ClothArmor => ClothArmor::new,
            ItemId::ControlWard => ControlWard::new,
            ItemId::CorruptingPotion => CorruptingPotion::new,
            ItemId::CosmicDrive => CosmicDrive::new,
            ItemId::CosmicDriveArena => CosmicDriveArena::new,
            ItemId::CrimsonLucidity => CrimsonLucidity::new,
            ItemId::CrownOfTheShatteredQueen => CrownOfTheShatteredQueen::new,
            ItemId::CrownOfTheShatteredQueenArena => CrownOfTheShatteredQueenArena::new,
            ItemId::CrownOfTheShatteredQueenU44 => CrownOfTheShatteredQueenU44::new,
            ItemId::CrownOfTheShatteredQueenU66 => CrownOfTheShatteredQueenU66::new,
            ItemId::CrueltyU44 => CrueltyU44::new,
            ItemId::CrueltyU66 => CrueltyU66::new,
            ItemId::Cryptbloom => Cryptbloom::new,
            ItemId::CryptbloomArena => CryptbloomArena::new,
            ItemId::CrystallineBracer => CrystallineBracer::new,
            ItemId::Cull => Cull::new,
            ItemId::CyclonicSlicers => CyclonicSlicers::new,
            ItemId::Dagger => Dagger::new,
            ItemId::DarkSeal => DarkSeal::new,
            ItemId::DarksteelTalonsU44 => DarksteelTalonsU44::new,
            ItemId::Dawncore => Dawncore::new,
            ItemId::DawncoreArena => DawncoreArena::new,
            ItemId::DawncoreU32 => DawncoreU32::new,
            ItemId::DeadMansPlate => DeadMansPlate::new,
            ItemId::DeadMansPlateArena => DeadMansPlateArena::new,
            ItemId::DeathbladeArena => DeathbladeArena::new,
            ItemId::DeathfireGrasp => DeathfireGrasp::new,
            ItemId::DeathsDance => DeathsDance::new,
            ItemId::DeathsDanceArena => DeathsDanceArena::new,
            ItemId::DecapitatorU44 => DecapitatorU44::new,
            ItemId::DeepFreeze => DeepFreeze::new,
            ItemId::DemonicEmbrace => DemonicEmbrace::new,
            ItemId::DemonicEmbraceArena => DemonicEmbraceArena::new,
            ItemId::DemonicEmbraceU44 => DemonicEmbraceU44::new,
            ItemId::DemonKingsCrownU44 => DemonKingsCrownU44::new,
            ItemId::DemonKingsCrownU66 => DemonKingsCrownU66::new,
            ItemId::DetonationOrbU44 => DetonationOrbU44::new,
            ItemId::DiademOfSongs => DiademOfSongs::new,
            ItemId::DiademOfSongsArena => DiademOfSongsArena::new,
            ItemId::DiademOfSongsU32 => DiademOfSongsU32::new,
            ItemId::DiamondTippedSpearU44 => DiamondTippedSpearU44::new,
            ItemId::DisabledRecall => DisabledRecall::new,
            ItemId::DivineSunderer => DivineSunderer::new,
            ItemId::DivineSundererArena => DivineSundererArena::new,
            ItemId::DivineSundererU44 => DivineSundererU44::new,
            ItemId::DoransBlade => DoransBlade::new,
            ItemId::DoransRing => DoransRing::new,
            ItemId::DoransShield => DoransShield::new,
            ItemId::DoubleBunBunBarrage => DoubleBunBunBarrage::new,
            ItemId::DragonheartU44 => DragonheartU44::new,
            ItemId::DreamMaker => DreamMaker::new,
            ItemId::DuskAndDawn => DuskAndDawn::new,
            ItemId::DuskAndDawnArena => DuskAndDawnArena::new,
            ItemId::DuskbladeOfDraktharr => DuskbladeOfDraktharr::new,
            ItemId::DuskbladeOfDraktharrArena => DuskbladeOfDraktharrArena::new,
            ItemId::DuskbladeOfDraktharrU44 => DuskbladeOfDraktharrU44::new,
            ItemId::EchoesOfHelia => EchoesOfHelia::new,
            ItemId::EchoesOfHeliaArena => EchoesOfHeliaArena::new,
            ItemId::EchoesOfHeliaU32 => EchoesOfHeliaU32::new,
            ItemId::EchoingBatblades => EchoingBatblades::new,
            ItemId::Eclipse => Eclipse::new,
            ItemId::EclipseArena => EclipseArena::new,
            ItemId::EdgeOfNight => EdgeOfNight::new,
            ItemId::EdgeOfNightArena => EdgeOfNightArena::new,
            ItemId::EleisasMiracleU44 => EleisasMiracleU44::new,
            ItemId::ElixirOfAvarice => ElixirOfAvarice::new,
            ItemId::ElixirOfForce => ElixirOfForce::new,
            ItemId::ElixirOfIron => ElixirOfIron::new,
            ItemId::ElixirOfSkill => ElixirOfSkill::new,
            ItemId::ElixirOfSorcery => ElixirOfSorcery::new,
            ItemId::ElixirOfWrath => ElixirOfWrath::new,
            ItemId::Emberknife => Emberknife::new,
            ItemId::EmpyreanPromiseU44 => EmpyreanPromiseU44::new,
            ItemId::EndlessHunger => EndlessHunger::new,
            ItemId::EndlessHungerArena => EndlessHungerArena::new,
            ItemId::EnhancedLuckyDice => EnhancedLuckyDice::new,
            ItemId::EnhancedRecall => EnhancedRecall::new,
            ItemId::EnvelopingLight => EnvelopingLight::new,
            ItemId::EssenceReaver => EssenceReaver::new,
            ItemId::EssenceReaverArena => EssenceReaverArena::new,
            ItemId::Evenshroud => Evenshroud::new,
            ItemId::EvenshroudArena => EvenshroudArena::new,
            ItemId::Everfrost => Everfrost::new,
            ItemId::EverfrostArena => EverfrostArena::new,
            ItemId::EverfrostU44 => EverfrostU44::new,
            ItemId::EvolvedEmbershot => EvolvedEmbershot::new,
            ItemId::ExecutionersCalling => ExecutionersCalling::new,
            ItemId::ExperimentalHexplate => ExperimentalHexplate::new,
            ItemId::ExperimentalHexplateArena => ExperimentalHexplateArena::new,
            ItemId::ExplosiveEmbrace => ExplosiveEmbrace::new,
            ItemId::EyeOfTheHerald1104 => EyeOfTheHerald1104::new,
            ItemId::EyeOfTheHerald3513 => EyeOfTheHerald3513::new,
            ItemId::FaerieCharm => FaerieCharm::new,
            ItemId::FarsightAlteration => FarsightAlteration::new,
            ItemId::FatedAshes => FatedAshes::new,
            ItemId::FcLimitedExpress => FcLimitedExpress::new,
            ItemId::FiendhunterBolts => FiendhunterBolts::new,
            ItemId::FiendhunterBoltsArena => FiendhunterBoltsArena::new,
            ItemId::FiendishCodex => FiendishCodex::new,
            ItemId::Fimbulwinter => Fimbulwinter::new,
            ItemId::FimbulwinterArena => FimbulwinterArena::new,
            ItemId::FimbulwinterU32 => FimbulwinterU32::new,
            ItemId::FinalCityTransit => FinalCityTransit::new,
            ItemId::FlesheaterU44 => FlesheaterU44::new,
            ItemId::FlesheaterU66 => FlesheaterU66::new,
            ItemId::ForbiddenIdol => ForbiddenIdol::new,
            ItemId::ForceOfEntropyU44 => ForceOfEntropyU44::new,
            ItemId::ForceOfNature => ForceOfNature::new,
            ItemId::ForceOfNatureArena => ForceOfNatureArena::new,
            ItemId::ForeverForward => ForeverForward::new,
            ItemId::Fortification1501 => Fortification1501::new,
            ItemId::Fortification1521 => Fortification1521::new,
            ItemId::Frostfang => Frostfang::new,
            ItemId::FrozenHeart => FrozenHeart::new,
            ItemId::FrozenHeartArena => FrozenHeartArena::new,
            ItemId::FrozenHeartU32 => FrozenHeartU32::new,
            ItemId::FrozenMallet => FrozenMallet::new,
            ItemId::FulminationU44 => FulminationU44::new,
            ItemId::Galeforce => Galeforce::new,
            ItemId::GaleforceArena => GaleforceArena::new,
            ItemId::GaleforceU44 => GaleforceU44::new,
            ItemId::GamblersBladeU44 => GamblersBladeU44::new,
            ItemId::GamblersBladeU66 => GamblersBladeU66::new,
            ItemId::GangplankPlaceholder => GangplankPlaceholder::new,
            ItemId::GargoyleStoneplate => GargoyleStoneplate::new,
            ItemId::GargoyleStoneplateArena => GargoyleStoneplateArena::new,
            ItemId::GargoyleStoneplateU44 => GargoyleStoneplateU44::new,
            ItemId::GargoyleStoneplateU66 => GargoyleStoneplateU66::new,
            ItemId::GatlingBunnyGuns => GatlingBunnyGuns::new,
            ItemId::Ghostcrawlers => Ghostcrawlers::new,
            ItemId::GhostcrawlersArena => GhostcrawlersArena::new,
            ItemId::GiantsBelt => GiantsBelt::new,
            ItemId::GiantsBeltArena => GiantsBeltArena::new,
            ItemId::GlacialBuckler => GlacialBuckler::new,
            ItemId::GlowingMote => GlowingMote::new,
            ItemId::GlowingMoteArena => GlowingMoteArena::new,
            ItemId::GoldenSpatulaU99 => GoldenSpatulaU99::new,
            ItemId::GoldStatAnvilVoucherArena => GoldStatAnvilVoucherArena::new,
            ItemId::Goredrinker => Goredrinker::new,
            ItemId::GoredrinkerArena => GoredrinkerArena::new,
            ItemId::GrizzlySmash => GrizzlySmash::new,
            ItemId::GuardianAngel => GuardianAngel::new,
            ItemId::GuardianAngelArena => GuardianAngelArena::new,
            ItemId::GuardiansAmulet => GuardiansAmulet::new,
            ItemId::GuardiansBlade => GuardiansBlade::new,
            ItemId::GuardiansBladeArena => GuardiansBladeArena::new,
            ItemId::GuardiansDirkArena => GuardiansDirkArena::new,
            ItemId::GuardiansHammer => GuardiansHammer::new,
            ItemId::GuardiansHammerArena => GuardiansHammerArena::new,
            ItemId::GuardiansHorn => GuardiansHorn::new,
            ItemId::GuardiansHornArena => GuardiansHornArena::new,
            ItemId::GuardiansOrb => GuardiansOrb::new,
            ItemId::GuardiansOrbArena => GuardiansOrbArena::new,
            ItemId::GuardiansShroud => GuardiansShroud::new,
            ItemId::GuidingHex => GuidingHex::new,
            ItemId::GuinsoosRageblade => GuinsoosRageblade::new,
            ItemId::GuinsoosRagebladeArena => GuinsoosRagebladeArena::new,
            ItemId::GunmetalGreaves => GunmetalGreaves::new,
            ItemId::Gusto => Gusto::new,
            ItemId::GustwalkerHatchling1102 => GustwalkerHatchling1102::new,
            ItemId::GustwalkerHatchling1106 => GustwalkerHatchling1106::new,
            ItemId::Hailblade => Hailblade::new,
            ItemId::HamstringerU44 => HamstringerU44::new,
            ItemId::HarrowingCrescent => HarrowingCrescent::new,
            ItemId::HauntingGuise => HauntingGuise::new,
            ItemId::HealthPotion => HealthPotion::new,
            ItemId::HearthboundAxe => HearthboundAxe::new,
            ItemId::Heartsteel => Heartsteel::new,
            ItemId::HeartsteelArena => HeartsteelArena::new,
            ItemId::HellfireHatchet => HellfireHatchet::new,
            ItemId::HemomancersHelmU44 => HemomancersHelmU44::new,
            ItemId::HexboltCompanionU44 => HexboltCompanionU44::new,
            ItemId::Hexdrinker => Hexdrinker::new,
            ItemId::HexopticsC44 => HexopticsC44::new,
            ItemId::HexopticsC44Arena => HexopticsC44Arena::new,
            ItemId::HextechAlternator => HextechAlternator::new,
            ItemId::HextechGunblade => HextechGunblade::new,
            ItemId::HextechGunbladeArena => HextechGunbladeArena::new,
            ItemId::HextechGunbladeU66 => HextechGunbladeU66::new,
            ItemId::HextechRocketbelt => HextechRocketbelt::new,
            ItemId::HextechRocketbeltArena => HextechRocketbeltArena::new,
            ItemId::HollowRadiance => HollowRadiance::new,
            ItemId::HollowRadianceArena => HollowRadianceArena::new,
            ItemId::HoppedUpHex => HoppedUpHex::new,
            ItemId::HorizonFocus => HorizonFocus::new,
            ItemId::HorizonFocusArena => HorizonFocusArena::new,
            ItemId::Hubris126697 => Hubris126697::new,
            ItemId::Hubris6697 => Hubris6697::new,
            ItemId::HubrisArena => HubrisArena::new,
            ItemId::Hullbreaker => Hullbreaker::new,
            ItemId::HullbreakerArena => HullbreakerArena::new,
            ItemId::IceblastArmor => IceblastArmor::new,
            ItemId::IcebornGauntlet => IcebornGauntlet::new,
            ItemId::IcebornGauntletArena => IcebornGauntletArena::new,
            ItemId::ImmortalShieldbow => ImmortalShieldbow::new,
            ItemId::ImmortalShieldbowArena => ImmortalShieldbowArena::new,
            ItemId::ImperialMandate => ImperialMandate::new,
            ItemId::ImperialMandateArena => ImperialMandateArena::new,
            ItemId::ImperialMandateU32 => ImperialMandateU32::new,
            ItemId::InfinityEdge => InfinityEdge::new,
            ItemId::InfinityEdgeArena => InfinityEdgeArena::new,
            ItemId::InnervatingLocket => InnervatingLocket::new,
            ItemId::InnervatingLocketU44 => InnervatingLocketU44::new,
            ItemId::IonianBootsOfLucidity => IonianBootsOfLucidity::new,
            ItemId::IonianBootsOfLucidityArena => IonianBootsOfLucidityArena::new,
            ItemId::IronspikeWhip => IronspikeWhip::new,
            ItemId::JakShoTheProtean => JakShoTheProtean::new,
            ItemId::JakShoTheProteanArena => JakShoTheProteanArena::new,
            ItemId::JarvanIs => JarvanIs::new,
            ItemId::JinxsTriNamite => JinxsTriNamite::new,
            ItemId::JuiceOfHaste => JuiceOfHaste::new,
            ItemId::JuiceOfPower => JuiceOfPower::new,
            ItemId::JuiceOfVitality => JuiceOfVitality::new,
            ItemId::JungleQuest1204 => JungleQuest1204::new,
            ItemId::JungleQuest1209 => JungleQuest1209::new,
            ItemId::KaenicRookern => KaenicRookern::new,
            ItemId::KaenicRookernArena => KaenicRookernArena::new,
            ItemId::KalistasBlackSpear3599 => KalistasBlackSpear3599::new,
            ItemId::KalistasBlackSpear3600 => KalistasBlackSpear3600::new,
            ItemId::Kindlegem => Kindlegem::new,
            ItemId::KindlegemArena => KindlegemArena::new,
            ItemId::KinkouJitteU44 => KinkouJitteU44::new,
            ItemId::KircheisShard => KircheisShard::new,
            ItemId::KnightsVow => KnightsVow::new,
            ItemId::KnightsVowArena => KnightsVowArena::new,
            ItemId::KnightsVowU32 => KnightsVowU32::new,
            ItemId::KrakenSlayer => KrakenSlayer::new,
            ItemId::KrakenSlayerArena => KrakenSlayerArena::new,
            ItemId::LastWhisper => LastWhisper::new,
            ItemId::LeechingLeer => LeechingLeer::new,
            ItemId::LegendaryAssassinItemArena => LegendaryAssassinItemArena::new,
            ItemId::LegendaryFighterItemArena => LegendaryFighterItemArena::new,
            ItemId::LegendaryMageItemArena => LegendaryMageItemArena::new,
            ItemId::LegendaryMarksmanItemArena => LegendaryMarksmanItemArena::new,
            ItemId::LegendarySupportItemArena => LegendarySupportItemArena::new,
            ItemId::LegendaryTankItemArena => LegendaryTankItemArena::new,
            ItemId::LiandrysAnguishArena => LiandrysAnguishArena::new,
            ItemId::LiandrysTorment => LiandrysTorment::new,
            ItemId::LichBane => LichBane::new,
            ItemId::LichBaneArena => LichBaneArena::new,
            ItemId::Lifeline => Lifeline::new,
            ItemId::LifewellPendant => LifewellPendant::new,
            ItemId::LightningBraid => LightningBraid::new,
            ItemId::LightningRodU44 => LightningRodU44::new,
            ItemId::LightOfTheLion => LightOfTheLion::new,
            ItemId::LionesssLament => LionesssLament::new,
            ItemId::LockedWeaponSlot => LockedWeaponSlot::new,
            ItemId::LocketOfTheIronSolari => LocketOfTheIronSolari::new,
            ItemId::LocketOfTheIronSolariArena => LocketOfTheIronSolariArena::new,
            ItemId::LocketOfTheIronSolariU32 => LocketOfTheIronSolariU32::new,
            ItemId::LongSword => LongSword::new,
            ItemId::LordDominiksRegards => LordDominiksRegards::new,
            ItemId::LordDominiksRegardsArena => LordDominiksRegardsArena::new,
            ItemId::LostChapter => LostChapter::new,
            ItemId::LoversRicochet => LoversRicochet::new,
            ItemId::LucentSingularity => LucentSingularity::new,
            ItemId::LuckyDice => LuckyDice::new,
            ItemId::LudensEcho => LudensEcho::new,
            ItemId::LudensEchoArena => LudensEchoArena::new,
            ItemId::Malignance => Malignance::new,
            ItemId::MalignanceArena => MalignanceArena::new,
            ItemId::Manamune => Manamune::new,
            ItemId::ManamuneArena => ManamuneArena::new,
            ItemId::ManamuneU32 => ManamuneU32::new,
            ItemId::MawOfMalmortius => MawOfMalmortius::new,
            ItemId::MawOfMalmortiusArena => MawOfMalmortiusArena::new,
            ItemId::MejaisSoulstealer => MejaisSoulstealer::new,
            ItemId::MeowMeow => MeowMeow::new,
            ItemId::MercurialScimitar => MercurialScimitar::new,
            ItemId::MercurialScimitarArena => MercurialScimitarArena::new,
            ItemId::MercurysTreads => MercurysTreads::new,
            ItemId::MercurysTreadsArena => MercurysTreadsArena::new,
            ItemId::MidLaneQuest1201 => MidLaneQuest1201::new,
            ItemId::MidLaneQuest1206 => MidLaneQuest1206::new,
            ItemId::MikaelsBlessing => MikaelsBlessing::new,
            ItemId::MikaelsBlessingArena => MikaelsBlessingArena::new,
            ItemId::MikaelsBlessingU32 => MikaelsBlessingU32::new,
            ItemId::MinionDematerializer => MinionDematerializer::new,
            ItemId::MirageBladeU44 => MirageBladeU44::new,
            ItemId::MobilityBoots => MobilityBoots::new,
            ItemId::MoonflairSpellbladeU44 => MoonflairSpellbladeU44::new,
            ItemId::MoonstoneRenewer => MoonstoneRenewer::new,
            ItemId::MoonstoneRenewerArena => MoonstoneRenewerArena::new,
            ItemId::MoonstoneRenewerU32 => MoonstoneRenewerU32::new,
            ItemId::Morellonomicon => Morellonomicon::new,
            ItemId::MorellonomiconArena => MorellonomiconArena::new,
            ItemId::MortalReminder => MortalReminder::new,
            ItemId::MortalReminderArena => MortalReminderArena::new,
            ItemId::MosstomperSeedling1103 => MosstomperSeedling1103::new,
            ItemId::MosstomperSeedling1105 => MosstomperSeedling1105::new,
            ItemId::MultitoolArena => MultitoolArena::new,
            ItemId::Muramana => Muramana::new,
            ItemId::MuramanaArena => MuramanaArena::new,
            ItemId::MuramanaU32 => MuramanaU32::new,
            ItemId::NashorsTooth => NashorsTooth::new,
            ItemId::NashorsToothArena => NashorsToothArena::new,
            ItemId::NavoriFlickerblade => NavoriFlickerblade::new,
            ItemId::NavoriFlickerbladesArena => NavoriFlickerbladesArena::new,
            ItemId::NeedlesslyLargeRod => NeedlesslyLargeRod::new,
            ItemId::NeedlesslyLargeRodArena => NeedlesslyLargeRodArena::new,
            ItemId::NegatronCloak => NegatronCloak::new,
            ItemId::NegatronCloakArena => NegatronCloakArena::new,
            ItemId::NeverendingMobstomper => NeverendingMobstomper::new,
            ItemId::NightHarvester => NightHarvester::new,
            ItemId::NightHarvesterArena => NightHarvesterArena::new,
            ItemId::NightHarvesterU44 => NightHarvesterU44::new,
            ItemId::Noonquiver => Noonquiver::new,
            ItemId::NullMagicMantle => NullMagicMantle::new,
            ItemId::OblivionOrb => OblivionOrb::new,
            ItemId::ObsidianCleaverArena => ObsidianCleaverArena::new,
            ItemId::ObsidianEdge => ObsidianEdge::new,
            ItemId::Opportunity => Opportunity::new,
            ItemId::OpportunityArena => OpportunityArena::new,
            ItemId::OracleLens => OracleLens::new,
            ItemId::Overcharged1507 => Overcharged1507::new,
            ItemId::Overcharged1523 => Overcharged1523::new,
            ItemId::Overerchargedha => Overerchargedha::new,
            ItemId::Overgrowth => Overgrowth::new,
            ItemId::OverlordsBloodmail => OverlordsBloodmail::new,
            ItemId::OverlordsBloodmailU44 => OverlordsBloodmailU44::new,
            ItemId::OwoBlaster => OwoBlaster::new,
            ItemId::PartyFavor => PartyFavor::new,
            ItemId::PauldronsOfWhiterock => PauldronsOfWhiterock::new,
            ItemId::PawPrintPoisoner => PawPrintPoisoner::new,
            ItemId::PenetratingBullets => PenetratingBullets::new,
            ItemId::Perplexity => Perplexity::new,
            ItemId::Phage => Phage::new,
            ItemId::PhantomDancer => PhantomDancer::new,
            ItemId::PhantomDancerArena => PhantomDancerArena::new,
            ItemId::PhreakishGusto => PhreakishGusto::new,
            ItemId::Pickaxe => Pickaxe::new,
            ItemId::PillorySwipe => PillorySwipe::new,
            ItemId::PlatedSteelcaps => PlatedSteelcaps::new,
            ItemId::PlatedSteelcapsArena => PlatedSteelcapsArena::new,
            ItemId::PoroSnax => PoroSnax::new,
            ItemId::PrismaticItemArena => PrismaticItemArena::new,
            ItemId::PrismaticStatVoucherArena => PrismaticStatVoucherArena::new,
            ItemId::ProfaneHydra => ProfaneHydra::new,
            ItemId::ProfaneHydraArena => ProfaneHydraArena::new,
            ItemId::ProtoplasmHarness => ProtoplasmHarness::new,
            ItemId::ProtoplasmHarnessArena => ProtoplasmHarnessArena::new,
            ItemId::ProwlersClaw => ProwlersClaw::new,
            ItemId::ProwlersClawArena => ProwlersClawArena::new,
            ItemId::ProwlersClawU44 => ProwlersClawU44::new,
            ItemId::PrumbissElectrocarver => PrumbissElectrocarver::new,
            ItemId::PuppeteerU44 => PuppeteerU44::new,
            ItemId::PyromancersCloakU44 => PyromancersCloakU44::new,
            ItemId::QuadORang => QuadORang::new,
            ItemId::QuestBot => QuestBot::new,
            ItemId::QuestJungle => QuestJungle::new,
            ItemId::QuestMid => QuestMid::new,
            ItemId::QuestSupport => QuestSupport::new,
            ItemId::QuestTop => QuestTop::new,
            ItemId::QuicksilverSash => QuicksilverSash::new,
            ItemId::RabadonsDeathcap => RabadonsDeathcap::new,
            ItemId::RabadonsDeathcapArena => RabadonsDeathcapArena::new,
            ItemId::RadiantField => RadiantField::new,
            ItemId::RadiantVirtue => RadiantVirtue::new,
            ItemId::RadiantVirtueArena => RadiantVirtueArena::new,
            ItemId::RadiantVirtueU44 => RadiantVirtueU44::new,
            ItemId::Rageknife => Rageknife::new,
            ItemId::RanduinsOmen => RanduinsOmen::new,
            ItemId::RanduinsOmenArena => RanduinsOmenArena::new,
            ItemId::RapidFirecannon => RapidFirecannon::new,
            ItemId::RapidFirecannonArena => RapidFirecannonArena::new,
            ItemId::RapidRabbitRaindown => RapidRabbitRaindown::new,
            ItemId::RavenousHydra => RavenousHydra::new,
            ItemId::RavenousHydraArena => RavenousHydraArena::new,
            ItemId::RealityFractureU44 => RealityFractureU44::new,
            ItemId::ReapersTollU44 => ReapersTollU44::new,
            ItemId::Recall => Recall::new,
            ItemId::Rectrix => Rectrix::new,
            ItemId::RecurveBow => RecurveBow::new,
            ItemId::RecurveBowArena => RecurveBowArena::new,
            ItemId::Redemption => Redemption::new,
            ItemId::RedemptionArena => RedemptionArena::new,
            ItemId::RedemptionU32 => RedemptionU32::new,
            ItemId::RefillablePotion => RefillablePotion::new,
            ItemId::RegicideU44 => RegicideU44::new,
            ItemId::ReinforcedArmor1502 => ReinforcedArmor1502::new,
            ItemId::ReinforcedArmor1505 => ReinforcedArmor1505::new,
            ItemId::ReinforcedArmor1506 => ReinforcedArmor1506::new,
            ItemId::RejuvenationBead => RejuvenationBead::new,
            ItemId::RelicShield => RelicShield::new,
            ItemId::ReverberationU44 => ReverberationU44::new,
            ItemId::Riftmaker => Riftmaker::new,
            ItemId::RiftmakerArena => RiftmakerArena::new,
            ItemId::RiteOfRuin => RiteOfRuin::new,
            ItemId::RodOfAges => RodOfAges::new,
            ItemId::RodOfAgesArena => RodOfAgesArena::new,
            ItemId::RodOfAgesU32 => RodOfAgesU32::new,
            ItemId::RubyCrystal => RubyCrystal::new,
            ItemId::RunaansHurricane => RunaansHurricane::new,
            ItemId::RunaansHurricaneArena => RunaansHurricaneArena::new,
            ItemId::RunecarverU44 => RunecarverU44::new,
            ItemId::RuneglaiveArena => RuneglaiveArena::new,
            ItemId::RunesteelSpaulders => RunesteelSpaulders::new,
            ItemId::RunicCompass => RunicCompass::new,
            ItemId::RylaisCrystalScepter => RylaisCrystalScepter::new,
            ItemId::RylaisCrystalScepterArena => RylaisCrystalScepterArena::new,
            ItemId::SanguineBladeArena => SanguineBladeArena::new,
            ItemId::SanguineGiftU44 => SanguineGiftU44::new,
            ItemId::SapphireCrystal => SapphireCrystal::new,
            ItemId::SavageSlice => SavageSlice::new,
            ItemId::ScarecrowEffigy => ScarecrowEffigy::new,
            ItemId::ScorchclawPup1101 => ScorchclawPup1101::new,
            ItemId::ScorchclawPup1107 => ScorchclawPup1107::new,
            ItemId::ScoutingAhead => ScoutingAhead::new,
            ItemId::ScoutsSlingshot => ScoutsSlingshot::new,
            ItemId::SearingShortbow => SearingShortbow::new,
            ItemId::SeekersArmguard => SeekersArmguard::new,
            ItemId::SeraphsEmbrace => SeraphsEmbrace::new,
            ItemId::SeraphsEmbraceArena => SeraphsEmbraceArena::new,
            ItemId::SeraphsEmbraceU32 => SeraphsEmbraceU32::new,
            ItemId::SerpentsFang => SerpentsFang::new,
            ItemId::SerpentsFangArena => SerpentsFangArena::new,
            ItemId::SerratedDirk => SerratedDirk::new,
            ItemId::SeryldasGrudge => SeryldasGrudge::new,
            ItemId::SeryldasGrudgeArena => SeryldasGrudgeArena::new,
            ItemId::Shadowflame => Shadowflame::new,
            ItemId::ShadowflameArena => ShadowflameArena::new,
            ItemId::ShardOfTrueIce => ShardOfTrueIce::new,
            ItemId::ShatteredArmguard => ShatteredArmguard::new,
            ItemId::Sheen => Sheen::new,
            ItemId::SheenArena => SheenArena::new,
            ItemId::ShieldOfMoltenStoneU44 => ShieldOfMoltenStoneU44::new,
            ItemId::ShieldOfMoltenStoneU66 => ShieldOfMoltenStoneU66::new,
            ItemId::ShieldOfTheRakkor => ShieldOfTheRakkor::new,
            ItemId::ShieldSlam => ShieldSlam::new,
            ItemId::ShurelyasBattlesong => ShurelyasBattlesong::new,
            ItemId::ShurelyasBattlesongArena => ShurelyasBattlesongArena::new,
            ItemId::ShurelyasBattlesongU32 => ShurelyasBattlesongU32::new,
            ItemId::SilvermereDawn => SilvermereDawn::new,
            ItemId::SilvermereDawnArena => SilvermereDawnArena::new,
            ItemId::SinEater => SinEater::new,
            ItemId::SlightlyMagicalFootwear => SlightlyMagicalFootwear::new,
            ItemId::SmallPartyFavor => SmallPartyFavor::new,
            ItemId::SolsticeSleigh => SolsticeSleigh::new,
            ItemId::SorcerersShoes => SorcerersShoes::new,
            ItemId::SorcerersShoesArena => SorcerersShoesArena::new,
            ItemId::SoundWave => SoundWave::new,
            ItemId::SpearOfShojin => SpearOfShojin::new,
            ItemId::SpearOfShojinArena => SpearOfShojinArena::new,
            ItemId::SpectralCutlass => SpectralCutlass::new,
            ItemId::SpectralCutlassArena => SpectralCutlassArena::new,
            ItemId::SpectralSickle => SpectralSickle::new,
            ItemId::SpectresCowl => SpectresCowl::new,
            ItemId::SpellslingersShoes => SpellslingersShoes::new,
            ItemId::SpellthiefsEdge => SpellthiefsEdge::new,
            ItemId::SpiritVisage => SpiritVisage::new,
            ItemId::SpiritVisageArena => SpiritVisageArena::new,
            ItemId::StaffOfFlowingWater => StaffOfFlowingWater::new,
            ItemId::StaffOfFlowingWaterArena => StaffOfFlowingWaterArena::new,
            ItemId::StaffOfFlowingWaterU32 => StaffOfFlowingWaterU32::new,
            ItemId::StatBonus => StatBonus::new,
            ItemId::StatBonusArena => StatBonusArena::new,
            ItemId::StatikkShiv => StatikkShiv::new,
            ItemId::StatikkShivArena => StatikkShivArena::new,
            ItemId::StatikkSword => StatikkSword::new,
            ItemId::StealthWard2056 => StealthWard2056::new,
            ItemId::StealthWard3340 => StealthWard3340::new,
            ItemId::SteelShoulderguards => SteelShoulderguards::new,
            ItemId::SteelSigil => SteelSigil::new,
            ItemId::SteelTempest => SteelTempest::new,
            ItemId::SteraksGage => SteraksGage::new,
            ItemId::SteraksGageArena => SteraksGageArena::new,
            ItemId::StirringWardstone => StirringWardstone::new,
            ItemId::Stormrazor3095 => Stormrazor3095::new,
            ItemId::Stormrazor3097 => Stormrazor3097::new,
            ItemId::StormrazorArena => StormrazorArena::new,
            ItemId::Stormsurge => Stormsurge::new,
            ItemId::StormsurgeArena => StormsurgeArena::new,
            ItemId::Stridebreaker => Stridebreaker::new,
            ItemId::StridebreakerArena => StridebreakerArena::new,
            ItemId::StructureBounty1516 => StructureBounty1516::new,
            ItemId::StructureBounty1517 => StructureBounty1517::new,
            ItemId::StructureBounty1518 => StructureBounty1518::new,
            ItemId::StructureBounty1519 => StructureBounty1519::new,
            ItemId::SunderedSky => SunderedSky::new,
            ItemId::SunderedSkyArena => SunderedSkyArena::new,
            ItemId::SunfireAegis => SunfireAegis::new,
            ItemId::SunfireAegisArena => SunfireAegisArena::new,
            ItemId::SuperMechArmor => SuperMechArmor::new,
            ItemId::SuperMechPowerField => SuperMechPowerField::new,
            ItemId::SupportQuest1203 => SupportQuest1203::new,
            ItemId::SupportQuest1208 => SupportQuest1208::new,
            ItemId::Swiftmarch => Swiftmarch::new,
            ItemId::SwordOfBlossomingDawn124011 => SwordOfBlossomingDawn124011::new,
            ItemId::SwordOfBlossomingDawn4011 => SwordOfBlossomingDawn4011::new,
            ItemId::SwordOfBlossomingDawnU66 => SwordOfBlossomingDawnU66::new,
            ItemId::SwordOfTheDivine => SwordOfTheDivine::new,
            ItemId::SwordOfTheDivineU44 => SwordOfTheDivineU44::new,
            ItemId::SwordOfTheDivineU66 => SwordOfTheDivineU66::new,
            ItemId::SymbioticSoles => SymbioticSoles::new,
            ItemId::SynchronizedSouls => SynchronizedSouls::new,
            ItemId::TalismanOfAscensionU44 => TalismanOfAscensionU44::new,
            ItemId::TargonsBuckler => TargonsBuckler::new,
            ItemId::TearOfTheGoddess => TearOfTheGoddess::new,
            ItemId::TearOfTheGoddessU32 => TearOfTheGoddessU32::new,
            ItemId::TempestsGauntlet => TempestsGauntlet::new,
            ItemId::TentacleSlam => TentacleSlam::new,
            ItemId::Terminus => Terminus::new,
            ItemId::TerminusArena => TerminusArena::new,
            ItemId::TheAnnihilator => TheAnnihilator::new,
            ItemId::TheBrutalizer => TheBrutalizer::new,
            ItemId::TheCollector => TheCollector::new,
            ItemId::TheCollectorArena => TheCollectorArena::new,
            ItemId::TheCollectorU66 => TheCollectorU66::new,
            ItemId::TheGoldenSpatula => TheGoldenSpatula::new,
            ItemId::TheGoldenSpatulaArena => TheGoldenSpatulaArena::new,
            ItemId::TheGoldenSpatulaU66 => TheGoldenSpatulaU66::new,
            ItemId::Thornmail => Thornmail::new,
            ItemId::ThornmailArena => ThornmailArena::new,
            ItemId::ThornmailU32 => ThornmailU32::new,
            ItemId::Tiamat => Tiamat::new,
            ItemId::TIBBERS => TIBBERS::new,
            ItemId::TIBBERSBEEGEdition => TIBBERSBEEGEdition::new,
            ItemId::TitanicHydra => TitanicHydra::new,
            ItemId::TitanicHydraArena => TitanicHydraArena::new,
            ItemId::TopLaneQuest1200 => TopLaneQuest1200::new,
            ItemId::TopLaneQuest1221 => TopLaneQuest1221::new,
            ItemId::TopLaneQuest1222 => TopLaneQuest1222::new,
            ItemId::TotalBiscuitOfEverlastingWill => TotalBiscuitOfEverlastingWill::new,
            ItemId::TowerPowerUp => TowerPowerUp::new,
            ItemId::Trailblazer => Trailblazer::new,
            ItemId::TrailblazerArena => TrailblazerArena::new,
            ItemId::TrailblazerU32 => TrailblazerU32::new,
            ItemId::TrinityForce => TrinityForce::new,
            ItemId::TrinityForceArena => TrinityForceArena::new,
            ItemId::Tunneler => Tunneler::new,
            ItemId::TurboChemtankU44 => TurboChemtankU44::new,
            ItemId::TurretPlating => TurretPlating::new,
            ItemId::TwilightsEdgeU44 => TwilightsEdgeU44::new,
            ItemId::TwinMaskU44 => TwinMaskU44::new,
            ItemId::UmbralGlaive => UmbralGlaive::new,
            ItemId::UnceasingCyclone => UnceasingCyclone::new,
            ItemId::UnendingDespair => UnendingDespair::new,
            ItemId::UnendingDespairArena => UnendingDespairArena::new,
            ItemId::Unknown1205 => Unknown1205::new,
            ItemId::Unknown1210 => Unknown1210::new,
            ItemId::Unknown1211 => Unknown1211::new,
            ItemId::Unknown1212 => Unknown1212::new,
            ItemId::Unknown1213 => Unknown1213::new,
            ItemId::Unknown1214 => Unknown1214::new,
            ItemId::Unknown1215 => Unknown1215::new,
            ItemId::Unknown1216 => Unknown1216::new,
            ItemId::Unknown1217 => Unknown1217::new,
            ItemId::Unknown1218 => Unknown1218::new,
            ItemId::Unknown1219 => Unknown1219::new,
            ItemId::Unknown2008 => Unknown2008::new,
            ItemId::Unknown3901 => Unknown3901::new,
            ItemId::Unknown3902 => Unknown3902::new,
            ItemId::Unknown3903 => Unknown3903::new,
            ItemId::UnleashedTeleport => UnleashedTeleport::new,
            ItemId::UwuBlaster => UwuBlaster::new,
            ItemId::VampiricScepter => VampiricScepter::new,
            ItemId::VampiricScepterArena => VampiricScepterArena::new,
            ItemId::Vanguard => Vanguard::new,
            ItemId::VaynesChromablades => VaynesChromablades::new,
            ItemId::VeigarsTalismanOfAscensionU66 => VeigarsTalismanOfAscensionU66::new,
            ItemId::VerdantBarrier => VerdantBarrier::new,
            ItemId::VigilantWardstone => VigilantWardstone::new,
            ItemId::VoidStaff => VoidStaff::new,
            ItemId::VoidStaffArena => VoidStaffArena::new,
            ItemId::VoltaicCyclosword => VoltaicCyclosword::new,
            ItemId::VoltaicCycloswordArena => VoltaicCycloswordArena::new,
            ItemId::VortexGlove => VortexGlove::new,
            ItemId::WanderingStorms => WanderingStorms::new,
            ItemId::WardensEye => WardensEye::new,
            ItemId::WardensMail => WardensMail::new,
            ItemId::WarmogsArmor => WarmogsArmor::new,
            ItemId::WarmogsArmorU44 => WarmogsArmorU44::new,
            ItemId::WatchfulWardstone => WatchfulWardstone::new,
            ItemId::WhisperingCirclet => WhisperingCirclet::new,
            ItemId::WhisperingCircletArena => WhisperingCircletArena::new,
            ItemId::WhisperingCircletU32 => WhisperingCircletU32::new,
            ItemId::WingedDagger => WingedDagger::new,
            ItemId::WingedMoonplate => WingedMoonplate::new,
            ItemId::WintersApproach => WintersApproach::new,
            ItemId::WintersApproachArena => WintersApproachArena::new,
            ItemId::WintersApproachU32 => WintersApproachU32::new,
            ItemId::WitsEnd => WitsEnd::new,
            ItemId::WitsEndArena => WitsEndArena::new,
            ItemId::WoogletsWitchcapArena => WoogletsWitchcapArena::new,
            ItemId::WordlessPromise => WordlessPromise::new,
            ItemId::WorldAtlas => WorldAtlas::new,
            ItemId::YoumuusGhostblade => YoumuusGhostblade::new,
            ItemId::YoumuusGhostbladeArena => YoumuusGhostbladeArena::new,
            ItemId::YourCut => YourCut::new,
            ItemId::YunTalWildarrows => YunTalWildarrows::new,
            ItemId::YunTalWildarrowsArena => YunTalWildarrowsArena::new,
            ItemId::Yuumibot => Yuumibot::new,
            ItemId::YuumibotFinalFinal => YuumibotFinalFinal::new,
            ItemId::ZazZaksRealmspike => ZazZaksRealmspike::new,
            ItemId::Zeal => Zeal::new,
            ItemId::ZekesConvergence => ZekesConvergence::new,
            ItemId::ZekesConvergenceArena => ZekesConvergenceArena::new,
            ItemId::ZekesConvergenceU32 => ZekesConvergenceU32::new,
            ItemId::ZephyrArena => ZephyrArena::new,
            ItemId::ZephyrU66 => ZephyrU66::new,
            ItemId::ZhonyasHourglass => ZhonyasHourglass::new,
            ItemId::ZhonyasHourglassArena => ZhonyasHourglassArena::new,
        }
    }

    /// Runs all item generators, stopping the execution if one of them fails
    pub fn run_all() -> MayFail {
        ItemId::VALUES
            .into_par_iter()
            .for_each(|item_id| match Self::run(item_id) {
                Ok(data) => data
                    .current_data
                    .into_file(SaveTo::Internal(item_id.entity()).path())
                    .unwrap(),
                Err(e) => panic!("Unable to run generator for {item_id:?}, Error: {e}"),
            });
        Ok(())
    }

    pub fn clean() -> MayFail {
        for item_id in ItemId::VALUES {
            let generator_path = SaveTo::Generator(item_id.entity()).path();
            let path = SaveTo::Internal(item_id.entity()).path();
            let json = Value::from_file(&path)?;

            if let Some(version) = json.get("version")
                && let Some(version) = version.as_str()
                && version != ENV_CONFIG.lol_version
            {
                if let Ok(true) = std::fs::exists(&generator_path) {
                    println!("ItemId::{item_id:?} is stable but no longer available");
                    continue;
                }
            }

            std::fs::remove_file(path)?;
            std::fs::remove_file(generator_path)?;
        }
        Ok(())
    }

    /// Runs some item generator, taking its generated data and saving to an internal folder
    pub fn run(item_id: ItemId) -> MayFail<ItemData> {
        let riot_id = &item_id.to_riot_id().to_string();
        let meraki_data =
            MerakiItem::from_file(SaveTo::MerakiCache(Tag::Items, riot_id).path()).ok();
        let riot_data = RiotCdnItem::from_file(SaveTo::RiotCache(Tag::Items, riot_id).path())?;
        let current_data = Item::from_file(SaveTo::Internal(item_id.entity()).path())?;

        let function = Self::function(item_id);
        let generator = function(ItemData::new(meraki_data, riot_data, current_data));
        Ok(generator.generate()?)
    }
}
