use super::decl_runes::*;
crate::decl_runes!(
	ArcaneComet,
	BonePlating,
	CoupDeGrace,
	CutDown,
	DeathfireTouch,
	Electrocute,
	GraspOfTheUndying,
	LastStand,
	NullifyingOrb,
	PhaseRush,
	PressTheAttack,
	Scorch,
	SecondWind,
	ShieldBash,
	StormraidersSurge,
	SuddenImpact
);