[package]
name = "tutorlolv2_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", default-features = false, features = ["derive"] }
paste = "1.0.15"
serde = { version = "1.0.219", features = ["derive"] }
