name: Run Writers Test (No Files)

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test-writers:
    runs-on: ubuntu-latest

    env:
      CDN_ENDPOINT_CHAMPIONS: ${{ secrets.CDN_ENDPOINT_CHAMPIONS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run test writers without file I/O
        run: |
          cargo test --test writers -- --fetch-remote="${CDN_ENDPOINT_CHAMPIONS}"
